language: c
before_install:
  # Install nim
  - git clone -b devel git://github.com/nim-lang/Nim.git --depth 1
  - cd Nim
  - git clone --depth 1 git://github.com/nim-lang/csources
  - cd csources && sh build.sh
  - cd ..
  - bin/nim c koch
  - sed -i -e 's,cc = gcc,cc = clang,' config/nim.cfg
  - ./koch boot -d:release
  - export PATH=$PWD/bin:$PATH
  - ./koch nimble
  - cd ..
script:
  - nimble install -y
  - nim test
  
